name: fantasy11_flutter
description: fantasy11 - Fantacy Cricket UI Kit.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_framework: ^0.1.4
  google_fonts: ^2.1.0
  animations: ^2.0.0
  url_launcher: ^6.0.20
  modal_bottom_sheet: ^2.0.0
  flutter_rating_bar: ^4.0.0
  file_picker: ^4.2.2+1
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  confetti: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:

  color: "#FFFFFF"

  image: assets/logo.png
  fullscreen: true
